### ISSUE TITLE
Compatibility issue with original RSP1 

### ISSUE THREAD

**Issue by crushed-grapes** [SDRplay/examples#4]
I have an original RSP1 and and RSP2 (with the hi-z port).   This code works great with my RSP2 (for each of the antenna ports that I select) but when I try it with the RSP1 it errors out saying it can't find a compatible device.   Is there a constant I can set in the code to make it work with the RSP1 as well as the RSP2?

Also when using this code I am unable to up the gain as high as I can when using SDR Uno.   The -R value does not seem to give me the ability to turn the gain reduction down to 0 or anywhere close to it ( I think 20 is the best it will allow)  Any way to set the code to max out the gain?

Thanks!

**Comment by SDRplay** [comment]
The RSP1 is sometimes locked by Linux kernel modules. To address this...

lsmod | grep msi

hopefully this will not return anything, but if it does you will need to blacklist the modules. On Ubuntu you will need to add the following lines to the /etc/modprobe.d/blacklist.conf file...

blacklist sdr_msi3101
blacklist msi001
blacklist msi2500

Then reboot for the blacklist to take effect.

By default the IF gain reduction range is 20 to 59, this is because the low end of the range really has limited use. If you consult the API specification you can override this to use the 0-19 range, but it will have limited benefit.

Best regards,

Andy

**Comment by parity-error** [comment]
I have built a custom application around this 
 https://github.com/SDRplay/examples/blob/master/play_sdr.c
which works with the rsp1a devices.   Just bought an rsp1b in hopes noise floor would be better but the code does not see the rsp1b.  It reports 
mir_sdr_GetDevices sees 0 devices total.
mir_sdr_GetDevices sees 0 devices available.
I was under the impression that the rsp1b was compatible.  Any ideas on what I can do to make my code that works with rsp1a also work with rsp1b?     Thanks in advance.
